modLoader = "javafml"
loaderVersion = "[46,)"
license = "All Rights Reserved"
issueTrackerURL = "https://discord.gg/pHren9yxzW"
logoFile = "logo.png"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/relics-mod"
authors = "${mod_authors}"
description = '''Just a mod about useful relics with unique mechanics ;)'''

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20,1.21)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${mod_id}]]
    modId = "forge"
    mandatory = true
    versionRange = "[46,)"
    ordering = "NONE"
    side = "BOTH"